var a = document.getElementById("game1") 
var b = document.getElementById("game2") 
var c = document.getElementById("game3") 
var d = document.getElementById("game4")
var e = document.getElementById("game5") 
var f = document.getElementById("game6") 
var g = document.getElementById("game7")